from .all_functions.sin import f_dsin
from .all_functions.log import f_dlog
from .all_functions.exp import f_dexp
from .all_functions.cos import f_dcos
from .all_functions.tanh import f_dtanh
from .all_functions.tan import f_dtan
from .all_functions.sigmoid import f_dsigmoid
from .all_functions.relu import f_drelu
from .all_functions.softmax import f_dsoftmax
